#!/usr/bin/env bash
# curl test script generated by Apinox
# API: Reybi API v1.0.0
# Run with: bash curl_tests.sh

set -euo pipefail

BASE_URL="http://localhost:3000/v1"

echo "=== addresses ==="

# Create address (auth required) - POST
curl -s -w '\nHTTP Status: %{http_code}\n' -X POST -H 'Authorization: Bearer ${TOKEN}' -H 'Content-Type: application/json' -d '{}' 'http://localhost:3000/v1/addresses/user/{user_id}'

# Update address (auth required) - PUT
curl -s -w '\nHTTP Status: %{http_code}\n' -X PUT -H 'Authorization: Bearer ${TOKEN}' 'http://localhost:3000/v1/addresses/user/{user_id}'

echo "=== articles ==="

# Create article - POST
curl -s -w '\nHTTP Status: %{http_code}\n' -X POST -H 'Authorization: Bearer ${TOKEN}' -H 'Content-Type: application/json' -d '{}' 'http://localhost:3000/v1/articles/create'

# Get article by ID - GET
curl -s -w '\nHTTP Status: %{http_code}\n' -X GET -H 'Authorization: Bearer ${TOKEN}' 'http://localhost:3000/v1/articles/{id}'

# Update article - PUT
curl -s -w '\nHTTP Status: %{http_code}\n' -X PUT -H 'Authorization: Bearer ${TOKEN}' 'http://localhost:3000/v1/articles/{id}'

# Delete article - DELETE
curl -s -w '\nHTTP Status: %{http_code}\n' -X DELETE -H 'Authorization: Bearer ${TOKEN}' 'http://localhost:3000/v1/articles/{id}'

# List articles (public) - GET
curl -s -w '\nHTTP Status: %{http_code}\n' -X GET -H 'Authorization: Bearer ${TOKEN}' 'http://localhost:3000/v1/articles'

echo "=== auth ==="

# Register new user - POST
curl -s -w '\nHTTP Status: %{http_code}\n' -X POST -H 'Authorization: Bearer ${TOKEN}' -H 'Content-Type: application/json' -d '{}' 'http://localhost:3000/v1/auth/register'

# Request password reset - POST
curl -s -w '\nHTTP Status: %{http_code}\n' -X POST -H 'Authorization: Bearer ${TOKEN}' -H 'Content-Type: application/json' -d '{}' 'http://localhost:3000/v1/auth/reset-password'

# Login (Firebase token → JWT) - POST
curl -s -w '\nHTTP Status: %{http_code}\n' -X POST -H 'Authorization: Bearer ${TOKEN}' -H 'Content-Type: application/json' -d '{}' 'http://localhost:3000/v1/auth'

echo "=== banners ==="

# Create banner - POST
curl -s -w '\nHTTP Status: %{http_code}\n' -X POST -H 'Authorization: Bearer ${TOKEN}' -H 'Content-Type: application/json' -d '{}' 'http://localhost:3000/v1/banners/create'

# List banners by type - GET
curl -s -w '\nHTTP Status: %{http_code}\n' -X GET -H 'Authorization: Bearer ${TOKEN}' 'http://localhost:3000/v1/banners/type/{type}'

# List all banners (public) - GET
curl -s -w '\nHTTP Status: %{http_code}\n' -X GET -H 'Authorization: Bearer ${TOKEN}' 'http://localhost:3000/v1/banners'

echo "=== carts ==="

# Get user cart - GET
curl -s -w '\nHTTP Status: %{http_code}\n' -X GET -H 'Authorization: Bearer ${TOKEN}' 'http://localhost:3000/v1/carts/user/{user_id}'

# Add item to cart - POST
curl -s -w '\nHTTP Status: %{http_code}\n' -X POST -H 'Authorization: Bearer ${TOKEN}' -H 'Content-Type: application/json' -d '{}' 'http://localhost:3000/v1/carts/user/{user_id}'

# Remove cart item - DELETE
curl -s -w '\nHTTP Status: %{http_code}\n' -X DELETE -H 'Authorization: Bearer ${TOKEN}' 'http://localhost:3000/v1/carts/item/{id}'

echo "=== deposites ==="

# Get user deposites - GET
curl -s -w '\nHTTP Status: %{http_code}\n' -X GET -H 'Authorization: Bearer ${TOKEN}' 'http://localhost:3000/v1/deposites/user/{id}'

# List all deposites (admin) - GET
curl -s -w '\nHTTP Status: %{http_code}\n' -X GET -H 'Authorization: Bearer ${TOKEN}' 'http://localhost:3000/v1/deposites'

# Create deposite (auth required) - POST
curl -s -w '\nHTTP Status: %{http_code}\n' -X POST -H 'Authorization: Bearer ${TOKEN}' -H 'Content-Type: application/json' -d '{}' 'http://localhost:3000/v1/deposites'

echo "=== landfills ==="

# Update landfill (admin) - PUT
curl -s -w '\nHTTP Status: %{http_code}\n' -X PUT -H 'Authorization: Bearer ${TOKEN}' 'http://localhost:3000/v1/landfills/{id}'

# Delete landfill (admin) - DELETE
curl -s -w '\nHTTP Status: %{http_code}\n' -X DELETE -H 'Authorization: Bearer ${TOKEN}' 'http://localhost:3000/v1/landfills/{id}'

# List landfills (public) - GET
curl -s -w '\nHTTP Status: %{http_code}\n' -X GET -H 'Authorization: Bearer ${TOKEN}' 'http://localhost:3000/v1/landfills'

# Create landfill (admin) - POST
curl -s -w '\nHTTP Status: %{http_code}\n' -X POST -H 'Authorization: Bearer ${TOKEN}' -H 'Content-Type: application/json' -d '{}' 'http://localhost:3000/v1/landfills'

echo "=== orders ==="

# Cancel order (auth required) - DELETE
curl -s -w '\nHTTP Status: %{http_code}\n' -X DELETE -H 'Authorization: Bearer ${TOKEN}' 'http://localhost:3000/v1/orders/{id}'

# List all orders (admin) - GET
curl -s -w '\nHTTP Status: %{http_code}\n' -X GET -H 'Authorization: Bearer ${TOKEN}' 'http://localhost:3000/v1/orders'

# Get user orders - GET
curl -s -w '\nHTTP Status: %{http_code}\n' -X GET -H 'Authorization: Bearer ${TOKEN}' 'http://localhost:3000/v1/orders/user/{user_id}'

# Create order (auth required) - POST
curl -s -w '\nHTTP Status: %{http_code}\n' -X POST -H 'Authorization: Bearer ${TOKEN}' -H 'Content-Type: application/json' -d '{}' 'http://localhost:3000/v1/orders/user/{user_id}'

echo "=== products ==="

# Add product variant - POST
curl -s -w '\nHTTP Status: %{http_code}\n' -X POST -H 'Authorization: Bearer ${TOKEN}' -H 'Content-Type: application/json' -d '{}' 'http://localhost:3000/v1/products/variant/{id}'

# Create product - POST
curl -s -w '\nHTTP Status: %{http_code}\n' -X POST -H 'Authorization: Bearer ${TOKEN}' -H 'Content-Type: application/json' -d '{}' 'http://localhost:3000/v1/products/create'

# Get product by ID - GET
curl -s -w '\nHTTP Status: %{http_code}\n' -X GET -H 'Authorization: Bearer ${TOKEN}' 'http://localhost:3000/v1/products/{id}'

# Update product - PUT
curl -s -w '\nHTTP Status: %{http_code}\n' -X PUT -H 'Authorization: Bearer ${TOKEN}' -H 'Content-Type: application/json' -d '{}' 'http://localhost:3000/v1/products/{id}'

# Delete product - DELETE
curl -s -w '\nHTTP Status: %{http_code}\n' -X DELETE -H 'Authorization: Bearer ${TOKEN}' 'http://localhost:3000/v1/products/{id}'

# List products (public, no auth required) - GET
curl -s -w '\nHTTP Status: %{http_code}\n' -X GET -H 'Authorization: Bearer ${TOKEN}' 'http://localhost:3000/v1/products'

echo "=== profile ==="

# Get user profile - GET
curl -s -w '\nHTTP Status: %{http_code}\n' -X GET -H 'Authorization: Bearer ${TOKEN}' 'http://localhost:3000/v1/profile/{email}'

# Update user profile - PUT
curl -s -w '\nHTTP Status: %{http_code}\n' -X PUT -H 'Authorization: Bearer ${TOKEN}' -H 'Content-Type: application/json' -d '{}' 'http://localhost:3000/v1/profile/{email}'

echo "=== reviews ==="

# Create review (auth required) - POST
curl -s -w '\nHTTP Status: %{http_code}\n' -X POST -H 'Authorization: Bearer ${TOKEN}' -H 'Content-Type: application/json' -d '{}' 'http://localhost:3000/v1/reviews'

# Update review (auth required) - PUT
curl -s -w '\nHTTP Status: %{http_code}\n' -X PUT -H 'Authorization: Bearer ${TOKEN}' -H 'Content-Type: application/json' -d '{}' 'http://localhost:3000/v1/reviews/{id}'

echo "=== sallers ==="

# Get seller products - GET
curl -s -w '\nHTTP Status: %{http_code}\n' -X GET -H 'Authorization: Bearer ${TOKEN}' 'http://localhost:3000/v1/sallers/products/{id}'

echo "=== trash ==="

# Update trash type (admin) - PUT
curl -s -w '\nHTTP Status: %{http_code}\n' -X PUT -H 'Authorization: Bearer ${TOKEN}' 'http://localhost:3000/v1/trash/type/{id}'

# Delete trash type (admin) - DELETE
curl -s -w '\nHTTP Status: %{http_code}\n' -X DELETE -H 'Authorization: Bearer ${TOKEN}' 'http://localhost:3000/v1/trash/type/{id}'

# List trash types (public) - GET
curl -s -w '\nHTTP Status: %{http_code}\n' -X GET -H 'Authorization: Bearer ${TOKEN}' 'http://localhost:3000/v1/trash/types'

# Create trash type (admin) - POST
curl -s -w '\nHTTP Status: %{http_code}\n' -X POST -H 'Authorization: Bearer ${TOKEN}' -H 'Content-Type: application/json' -d '{}' 'http://localhost:3000/v1/trash/types'

